#! /bin/sh

##  generic bootstrap file for libraries -- Sam Hocevar <sam@zoy.org>
##  $Id: bootstrap 42 2007-04-06 17:41:15Z courmisch $

set -x
set -e

# Get a sane environment, just in case
LANG=C
export LANG
CYGWIN=binmode
export CYGWIN

# Remove old cruft
rm -f aclocal.m4 configure config.guess config.log config.sub config.cache config.h.in config.h compile ltmain.sh libtool ltconfig missing mkinstalldirs depcomp install-sh
rm -Rf autom4te.cache
(cd autotools && rm -f config.guess config.sub missing mkinstalldirs compile ltmain.sh depcomp install-sh)

autoreconf -sfi -Wall
